### ISSUE TITLE
GET Support Through AWS ALB -> gRPC Target Group

### ISSUE THREAD

**Issue by cnoon** [connectrpc/connect-swift#190]
First off, I have to say thanks for the amazing project! Connect is proving to be an amazing technology allowing us to bring gRPC to our frontend technology is a very scalable way.

## Intro
We're now exploring the possibility of switching from `POST` to `GET` requests with the approach laid out in the [Get Requests and Caching](https://connectrpc.com/docs/go/get-requests-and-caching/) docs. I've managed to get our Go server up and running with this as well as a Swift client where I'm modifying the request structure the same way the Go client is. 

> Is there a particular reason this feature is missing from the Connect-Swift library? If not, I would be willing to help pitch in to add it if that would be preferred.

I have a local setup where everything is working flawlessly. The goal for us (and most I'd assume) is to be able to leverage both our CDN and client side caches (`URLCache` in this case) without all the hurdles `POST` request types involve. 

## Issue
The roadblock we're running in to is that our AWS ALB is throwing a `464` when attempting to use a `GET` instead of a `POST`. From what we can tell thus far, this is all [by design from AWS](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-464-issues). We're fairly certain we're running in to the last condition, but was hoping you could help confirm.

```
The request protocol is an HTTP/2 and the request is not POST, while target group protocol version is a gRPC.
```

After digging around for a bit, I came across a few helpful tips, and they seem to be geared towards gRPC and not Connect, and this is where I could use some help.

- https://aws.amazon.com/pt/blogs/aws/new-application-load-balancer-support-for-end-to-end-http-2-and-grpc/
- https://github.com/grpc/grpc-node/issues/2093#issuecomment-1117969843
- https://stackoverflow.com/questions/60164162/load-balancing-grpc-requests-using-one-of-aws-load-balancers
- https://grpc.io/docs/guides/auth/

## Ask
Most of those threads leave me to believe that `credential channels` may be the solution here, but I can't find any documentation about them in the Connect protocol. Does the group have any guidance here? Is there an obvious problem here that I'm missing? Is this a gap in Connect? Any advice you could provide here would be most appreciated.

Cheers. 🍻

**Comment by rebello95** [comment]
👋🏽 @cnoon thank you for the kind words and for filing such a detailed issue!

> Is there a particular reason this feature is missing from the Connect-Swift library? If not, I would be willing to help pitch in to add it if that would be preferred.

> I have a local setup where everything is working flawlessly. The goal for us (and most I'd assume) is to be able to leverage both our CDN and client side caches (URLCache in this case) without all the hurdles POST request types involve.

GET support is for sure on our roadmap, I just haven't gotten around to implementing it yet 😄 if you have something working and are willing to contribute it, I'd be happy to review/collaborate.

For the second part of your inquiry regarding the AWS ALB - @akshayjshah would you mind chiming in here? I think you have more context than I do.

**Comment by akshayjshah** [comment]
Hey @cnoon - glad you're enjoying Connect! Feels especially nice coming from you - I used Alamofire in my one and only iOS application. 😍 

> The goal for us (and most I'd assume) is to be able to leverage both our CDN and client side caches (URLCache in this case) without all the hurdles POST request types involve.

That was definitely the most important goal. We also wanted to avoid CORS where possible and make RPC calls shareable as self-contained links.

> The roadblock we're running in to is that our AWS ALB is throwing a 464 when attempting to use a GET instead of a POST.

From the error messages, it looks like you have your ALB target group configured to use the gRPC protocol. Is that correct?

If so, I'm not surprised that it isn't working - if you're using `GET` requests, the client and server are speaking Connect's own RPC protocol instead of gRPC. The error message you're getting is a little confusing, but it seems to be correctly complaining that the request isn't using the gRPC protocol. You should be able to debug and fix this in two steps - first a debugging step, then a proper fix.

1. **Debugging**: Does the problem disappear if you change the protocol for your ALB target group to HTTP/2? As far as I understand ALBs, that _should_ work. If that works and traffic through your ALB is always going to use the Connect protocol, you can probably stop here - most of the ALB's gRPC-specific features seem designed to work around gRPC oddities that aren't relevant to the Connect protocol.
2. **Long-term fix**: If you want to support gRPC protocol requests to your ALB and need the gRPC-specific features, you should be able to set up multiple target groups and route between them using method and content-type. The target groups will both contain the same Go servers and port, but you'll want one target group configured to use the HTTP/2 protocol and one configured to use gRPC. Route HTTP GET requests and anything with the `application/proto`, `application/json`, `application/connect+proto`, or `application/connect+json` Content-Types to the HTTP/2 target group. Route anything else to the gRPC target group. At that point, all your requests should be succeeding, and you'll have the gRPC-specific ALB features working for any traffic using the gRPC protocol. (I haven't used ALBs myself, so hopefully this is all accurate - [this blog post](https://shailender-choudhary.medium.com/aws-alb-advanced-request-routing-315d26682ded) makes it sound like ALBs can handle this sort of routing.)

I'm very curious to know if this works, so please keep us updated! Also happy to chat in [Slack](https://buf.build/links/slack) if that's easier.

> Most of those threads leave me to believe that credential channels may be the solution here, but I can't find any documentation about them in the Connect protocol.

I don't think that's related, but I've been wrong about many things in the past 😉 Connect libraries make TLS really simple - just use an `https://` URL, as you would with `URLSession` or `net/http`.

**Comment by cnoon** [comment]
Thank you both for all the detailed explanation. I managed to get everything working by switching my ALB target group over to HTTP/2 and tinkering a lot with my security groups.

@rebello95 I'll start tinkering with GET support if I have time and will open a PR. Thanks again folks! 🍻

**Comment by akshayjshah** [comment]
🎉 Glad it's working!
