### ISSUE TITLE
URLSessionHTTPClient with GRPC support

### ISSUE THREAD

**Issue by aheze** [connectrpc/connect-swift#322]
Currently the library only supports `NIOHTTPClient` if you're using GRPC:

```swift
let client = ProtocolClient(
    httpClient: NIOHTTPClient(host: host, port: port, timeout: 10),
    config: ProtocolClientConfig(
        host: host,
        networkProtocol: .grpc,
        codec: ProtoCodec()
    )
)
```

This makes the current streaming response stop when the app is backgrounded.

Is there any way to use `URLSessionHTTPClient` with GRPC? This is to take advantage of `URLSessionConfiguration` which supports [continuing the task](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1407496-background) for a short while in the background.

Btw thanks for your work! Works smoothly and easy to set up 💪

**Comment by rebello95** [comment]
👋🏽 @aheze - the [documentation](https://connectrpc.com/docs/swift/using-clients#http-stack) notes that is not possible to use `URLSession` for gRPC because `URLSession` does not support/expose trailers. If `URLSession` exposes this in the future, we could support gRPC using that client 😃 

There are a few threads online asking about using NIO in the background. If you'd like to explore that more, I recommend you file an issue in the [NIO repository](https://github.com/apple/swift-nio).
