### ISSUE TITLE
No distinct error code for lack of internet access

### ISSUE THREAD

**Issue by aheze** [connectrpc/connect-swift#325]
Hey,

When I make a request and have internet turned off, Connect immediately errors out and throws `ConnectError(code: Connect.Code.unknown, message: Optional("empty error message from source"), exception: nil, details: [], metadata: [:])`.

Ideally it would let me know that this was due to no internet access. Is this possible?

**Comment by rebello95** [comment]
Thanks for flagging this @aheze.

@jhump do you know if there's a standardized way to communicate connectivity errors through Connect errors / status codes across other implementations?

**Comment by jhump** [comment]
The gRPC docs suggest using "Unavailable" for this sort of network error:
https://grpc.io/docs/guides/error/#network-failures

There are cases in the Go implementation where we do try to detect and classify some errors this way. However, there are no conformance test cases for this currently. The biggest issue with adding conformance cases is with HTTP/2: if we actually break a connection as part of the test case, we will likely impact more than just the intended test case since that single connection could be used by multiple concurrent RPCs and test cases. While it wouldn't be too hard to shoehorn in test cases that are HTTP-1.1-only, the value seems low for these since some implementations have to use completely different underlying libraries for HTTP 1.1 vs. HTTP/2 (like Node JS, Dart, C++), so tests passing for HTTP 1.1 don't necessarily imply that they'd pass for HTTP/2.

**Comment by rebello95** [comment]
Makes sense @jhump. I can look into converting network errors into the `unavailable` status in `ConnectError` (hopefully next week).
